resolver: lts-7.4
packages:
- '.'
- location:
    git: https://github.com/serokell/universum
    commit: 500a168f4cffb7b11d8fdcae30e837e937bf83e4
  extra-dep: true
nix:
  shell-file: shell.nix
extra-deps: []
flags: {}
extra-package-dbs: []
